任务1内容：完成第4章的学习及作业1，代码实现的过程上传到GitHub

[作业1](https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc)
前五十题必做,后五十题选做

DDL：20190808 8:00am

In [2]:
# 1. 导入numpy库并简写为 np
import numpy as np

In [ ]:
# 2. 打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

In [2]:
# 3. 创建一个长度为10的空向量
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 4. 如何找到任何一个数组的内存大小？
'%d bytes' % (arr1.size * arr1.itemsize)

'80 bytes'

In [4]:
# 5. 如何从命令行得到numpy中add函数的说明文档? 
# ?np.add
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [5]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量 
arr2 = np.zeros(10)
arr2[4] = 1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# 7. 创建一个值域范围从10到49的向量
arr3 = np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
# 8. 反转一个向量(第一个元素变为最后一个)
arr4 = np.arange(5)
print(arr4)
arr4 = arr4[::-1]
arr4
print(arr4)

[0 1 2 3 4]
[4 3 2 1 0]


In [8]:
# 9. 创建一个 3x3 并且值从0到8的矩阵
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
arr6 = np.array([1,2,0,0,4,0])
arr6_index = np.nonzero(arr6)
arr6_index

(array([0, 1, 4], dtype=int64),)

In [10]:
# 11. 创建一个 3x3 的单位矩阵
arr7 = np.eye(3,3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 12. 创建一个 3x3x3的随机数组
arr9 = np.random.random((3,3,3))
arr9

array([[[0.48681319, 0.56573695, 0.11973526],
        [0.24362207, 0.38458078, 0.31337226],
        [0.01362257, 0.67569794, 0.39310052]],

       [[0.00816097, 0.94624633, 0.59602787],
        [0.12991709, 0.24697473, 0.93999246],
        [0.01957023, 0.36848562, 0.66458457]],

       [[0.15317792, 0.89349154, 0.90416228],
        [0.52907336, 0.09637959, 0.61148378],
        [0.13676105, 0.59552466, 0.24938929]]])

In [12]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 
arr8 = np.random.random((10,10))
print(np.max(arr8))
print(np.min(arr8))

0.9985627727247476
0.03870800620233772


In [13]:
# 14. 创建一个长度为30的随机向量并找到它的平均值
arr9 = np.random.random(30)
print(np.mean(arr9))

0.45010826916603525


In [14]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0
arr10 = np.zeros((5,5))
arr11 = np.pad(arr10, pad_width=1, mode='constant', constant_values=1)
arr11
# arr10 = np,ones((5,5))
# arr10[1:-1,1:-1] = 0

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
# 16. 对于一个存在在数组，如何添加一个用0填充的边界?
arr12 = np.ones((5,5))
arr13 = np.pad(arr12, pad_width=1, mode='constant', constant_values=0)
arr13

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
# 17. 以下表达式运行的结果分别是什么?
# not a number, inf = infinity 
# np.nan 空值（但不是空对象），np.inf 无穷大/小

In [17]:
0 * np.nan

nan

In [18]:
np.nan == np.nan

False

In [19]:
np.inf> np.nan

False

In [20]:
np.nan - np.nan

nan

In [21]:
0.3 == 3 * 0.1 # python浮点数a与整型b相乘得到的数无法确定小数后有几位有效数字

False

In [22]:
3 * 0.1

0.30000000000000004

In [23]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
arr14 = np.diag(np.arange(1,5),k=-1)
arr14

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [24]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式
arr15 = np.ones((8,8),dtype=int)
arr15[1::2,::2] = 0
arr15[::2,1::2] = 0
arr15

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [25]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [26]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
# tile() is for constructing an array by repeating A the number of times given by reps
# tile(A, reps)
arr16 = np.array([[1,0],[0,1]])
np.tile(arr16, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [27]:
# 22. 对一个5x5的随机矩阵做归一化
arr17 = np.random.random((5,5))
print(arr17)
arr18 = (arr17 - arr17.min())/(arr17.max() - arr17.min())
print(arr18)

[[0.47414744 0.72343391 0.82335408 0.86951186 0.28965698]
 [0.65960634 0.66091622 0.67730911 0.24214211 0.17774255]
 [0.0897995  0.03363364 0.16737971 0.61541122 0.46748313]
 [0.28179412 0.65699745 0.71083171 0.71767323 0.38100158]
 [0.75191444 0.63780935 0.93065445 0.88734947 0.59030034]]
[[0.49108538 0.76899026 0.88038141 0.93183816 0.28541516]
 [0.6978352  0.69929546 0.71757028 0.23244551 0.1606528 ]
 [0.06261377 0.         0.1491003  0.64856643 0.48365599]
 [0.27664963 0.69492681 0.75494131 0.76256825 0.38724624]
 [0.8007404  0.67353589 1.         0.95172355 0.62057278]]


In [28]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
# ubyte是np内置的数据类型之一，表示无符号字节
color = np.dtype([("r", np.ubyte, 1), 
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

**numpy 内置的数据类型**

<img src='./numpy内置的数据类型.jpg' width=600>

In [29]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
# 一个5x2的矩阵
arr19 = np.arange(15).reshape(5,3)
arr20 = np.arange(6).reshape(3,2)
arr21 = np.dot(arr19,arr20)
print(arr21)
print(arr21.shape)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
(5, 2)


In [30]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反
arr22 = np.arange(1,11)
arr22[3:8] = - arr22[3:8]
arr22

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [31]:
# 26. 下面脚本运行后的结果是什么?

In [32]:
import numpy
print(sum(range(5),-1)) # 0+1+2+3+4+(-1)=9

9


In [ ]:
from numpy import *
print(sum(range(5),-1))
# 此时调用的是numpy.sum()，此处axis=-1，表示最后一个维度
# range(5)是待加和的数组，只有一维
# 故axis=-1就是将range(5)中的所有元素加起来，即0+1+2+3+4=10

In [34]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

In [5]:
Z = np.arange(10)
Z**Z # 合法

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [6]:
2 << Z >> 2 # ???

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [7]:
Z <- Z # 合法

array([False, False, False, False, False, False, False, False, False,
       False])

In [8]:
1j*Z # 合法

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [9]:
Z/1/1 # 合法

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
Z<Z>Z # 不合法

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# 28. 下列表达式的结果分别是什么?
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

In [12]:
np.array(0) / np.array(0)

D:\Software\Anaconda\installation\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [13]:
np.array(0) // np.array(0)

D:\Software\Anaconda\installation\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [14]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [18]:
# 29. 如何从零位对浮点数组做舍入 ? 
arr29_1 = np.random.random((2,3))
print(arr29_1)
arr29_2 = np.copysign(np.ceil(np.abs(arr29_1)),arr29_1)
print(arr29_2)

[[0.62993937 0.82359804 0.70045711]
 [0.3245246  0.07113657 0.18233817]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# 30. 如何找到两个数组中的共同元素?
arr30_1 = np.arange(12).reshape(3,4)
arr30_2 = np.arange(4,16).reshape(3,4)
np.intersect1d(arr30_1,arr30_2) # 1是one，不是字母l

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr30_1 = np.arange(12).reshape(3,4)
arr30_2 = np.arange(16).reshape(4,4)
np.intersect1d(arr30_1,arr30_2) # 两个数组的形状不同也能比较

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
# defaults = np.seterr(all="ignore")

In [21]:
# 32. 下面的表达式是正确的吗? 
np.sqrt(-1) == np.emath.sqrt(-1)

D:\Software\Anaconda\installation\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [22]:
np.sqrt(-1)

D:\Software\Anaconda\installation\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [23]:
np.emath.sqrt(-1)

1j

In [24]:
# 33. 如何得到昨天，今天，明天的日期? 
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09


In [27]:
# 34. 如何得到所有与2016年7月对应的日期？
arr34 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
arr34

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [91]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.arange(6).reshape(2,3)
B = A + 2
A = np.array(A,dtype='float') # 不改成浮点数，np.divide函数会报错
B = np.array(B,dtype='float')
print(A)
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)
print(B)

[[0. 1. 2.]
 [3. 4. 5.]]
[[2. 3. 4.]
 [5. 6. 7.]]
[[ -0.  -2.  -6.]
 [-12. -20. -30.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [28]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分
arr36 = np.random.randint(0,10,10)
arr36 - arr36%1

array([5, 9, 5, 6, 9, 1, 0, 8, 3, 7])

In [37]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
arr37 = 4 * np.random.random((5,5))
arr37

array([[0.62093211, 1.49952329, 2.55117606, 1.82027677, 3.35715196],
       [3.79282644, 1.60318087, 2.31725586, 2.85866262, 2.58027604],
       [2.57288455, 2.15922553, 0.02702236, 2.02773716, 2.83092293],
       [0.10547175, 1.65367996, 0.6629383 , 2.68882977, 3.64896112],
       [3.69935758, 0.57976569, 3.13944125, 2.54854398, 2.0386888 ]])

In [40]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组
# np.fromiter() is for creating a new 1-dimensional array from an iterable object.
def int_10():
     for x in range(10):
        yield x   # 生成器
arr38 = np.fromiter(int_10(),dtype='int32',count=-1)
print(arr38)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
arr39 = np.linspace(0,1,10)
arr39

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [41]:
# 40. 创建一个长度为10的随机向量，并将其排序
arr40 = np.random.random(10)
arr40.sort()
print(arr40)

[0.06407062 0.2065712  0.2648004  0.26959966 0.52376475 0.54264683
 0.58972938 0.83488698 0.88435626 0.91105941]


In [45]:
# 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
# add.reduce() is equivalent to sum()
arr41 = np.arange(5)
np.add.reduce(arr41)

10

In [48]:
# 42. 对于两个随机数组A和B，检查它们是否相等
A = np.random.random((2,3))
B = np.random.random((2,3))
np.allclose(A,B)  # assuming identical shape of the arrays and a tolerance for the comparison of values
# A == B 比较的是每个元素是否相等，返回每个元素的比较结果
# 方法2
# np.array_equal: checking both the shape and the element values, no tolerance (values have to be exactly equal)
# np.array_equal(A,B)

False

In [52]:
# 43. 创建一个只读数组(read-only)
Z = np.random.randn(2,3)
Z.flags.writeable = False # unwriteable means read-only

In [61]:
# (???)44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
arr44 = 20 * np.random.random((10,2))
X,Y = arr44[:,0], arr44[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[17.6069456   9.52431802 21.47290965 20.68797372  5.95467298 20.46450988
 11.54550668 19.25582199 23.28246365 17.38900737]
[0.29875065 0.27756362 0.57289815 0.63305896 1.47994134 0.57640758
 0.46641105 0.27135336 0.6366573  1.22423846]


In [70]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1
arr45 = np.random.randn(10)
arr45[arr45.argmax()] = 1
arr45

array([-0.18883674,  1.        ,  1.02431573, -2.11410231, -1.61753464,
       -1.24091773,  0.03929558, -0.58012026, -1.45234055, -1.62163281])

In [83]:
# 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5,endpoint=True),np.linspace(0,1,5,endpoint=True))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [75]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
X = np.random.random((2,3))
Y = np.random.random((2,3))
C = 1/(X-Y)
C

# 其他方法
# C = 1.0 / np.subtract.outer(X, Y)
# print(np.linalg.det(C))

array([[  1.41454614,  -5.90349141, -16.19801082],
       [  2.10650315,  -1.56983023,  -2.45589047]])

In [60]:
# 48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [59]:
# 49. 如何打印一个数组中的所有数值?
np.set_printoptions(threshold=np.nan)
arr49 = np.array([[1,2,3],[4,5,6]])
print(arr49)
# 可用于大量元素显示

[[1 2 3]
 [4 5 6]]


In [30]:
# 50. 给定标量时，如何找到数组中最接近标量的值？
arr50 = np.arange(10)
arr51 = np.arange(20,30)
index = (np.abs(arr50-arr51)).argmin() # arr50和arr51必须形状一致
arr50[index]

0

In [32]:
arr50 = np.arange(10,20)
arr51 = np.arange(20,30)
index = (np.abs(arr50-arr51)).argmin() # arr50和arr51必须形状一致
arr50[index]

10